package com.silverlake.mleb.mcb.entity;

// Generated Sep 3, 2013 5:42:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerEvent generated by hbm2java
 */
@Entity
@Table(name = "customer_state")
public class CustomerState implements java.io.Serializable {

	private Integer rowId;
	private String cif;
	private String description;
	private String mlebTranxId;
	private String orgId;
	private String usrId;
	private String deviceId;
	private String appVersion;
	private String state;
	private String stateValue;
	private String stateAction;
	private Date stateDatetime;
	private String referenceNo;
	private String channelCode;
	
	 

	public CustomerState() {
	}

 
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "CustomerState_id")
	@Column(name = "row_id", nullable=false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	 
 

	@Column(name = "mleb_tranx_id", length = 45)
	public String getMlebTranxId() {
		return this.mlebTranxId;
	}

	public void setMlebTranxId(String mlebTranxId) {
		this.mlebTranxId = mlebTranxId;
	}
 

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "state_datetime", length = 19)
	public Date getStateDatetime() {
		return this.stateDatetime;
	}

	public void setStateDatetime(Date stateDatetime) {
		this.stateDatetime = stateDatetime;
	}

	 

	@Column(name = "app_version", length = 45)
	public String getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

	@Column(name = "reference_no", length = 100, nullable = true)
	public String getReferenceNo() {
		return this.referenceNo;
	}

	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo;
	}

	@Column(name = "cif", length = 100)
	public String getCif() {
		return cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "device_id", length = 100, nullable = true)
	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	  
	@Column(name = "channel_code", length = 5, nullable = true)
	public String getChannelCode() {
		return channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	
	@Column(name = "org_id", length = 50)
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}


	@Column(name = "usr_id", length = 50)
	public String getUsrId() {
		return usrId;
	}


	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}


	@Column(name = "state", length = 50)
	public String getState() {
		return state;
	}


	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "state_value", length = 50)
	public String getStateValue() {
		return stateValue;
	}


	public void setStateValue(String stateValue) {
		this.stateValue = stateValue;
	}


	@Column(name = "state_action", length = 50)
	public String getStateAction() {
		return stateAction;
	}


	public void setStateAction(String stateAction) {
		this.stateAction = stateAction;
	}

	 
	
	
	

}
