package com.silverlake.mleb.mcb.entity;

// Generated Sep 26, 2013 11:52:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerAccOrder generated by hbm2java
 */
@Entity
@Table(name = "customer_acc_order")
public class CustomerAccOrder implements java.io.Serializable {

	private Integer rowId;
	private CustomerProfile customerProfile;
	private String accountNumber;
	private String accountOrder;
	private Date updateDate;

	public CustomerAccOrder() {
	}

	public CustomerAccOrder(CustomerProfile customerProfile,
			String accountOrder, Date updateDate) {
		this.customerProfile = customerProfile;
		this.accountOrder = accountOrder;
		this.updateDate = updateDate;
	}

	public CustomerAccOrder(CustomerProfile customerProfile,
			String accountNumber, String accountOrder, Date updateDate) {
		this.customerProfile = customerProfile;
		this.accountNumber = accountNumber;
		this.accountOrder = accountOrder;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "CustomerAccOrder_id")
	@Column(name = "row_id", nullable=false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cif", nullable = false)
	public CustomerProfile getCustomerProfile() {
		return this.customerProfile;
	}

	public void setCustomerProfile(CustomerProfile customerProfile) {
		this.customerProfile = customerProfile;
	}

	@Column(name = "account_number", length = 45)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "account_order", nullable = false, length = 45)
	public String getAccountOrder() {
		return this.accountOrder;
	}

	public void setAccountOrder(String accountOrder) {
		this.accountOrder = accountOrder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
