package com.silverlake.mleb.mcb.entity;

// Generated Sep 26, 2013 7:28:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerProfile generated by hbm2java
 */
@Entity
@Table(name = "customer_profile")
public class CustomerProfile implements java.io.Serializable {

	private String cif;
	private String createBy;
	private Date createDt;
	private String fullName;
	private String idNo;
	private String idType;
	private String loginId;
	private String orgId;
	private String orgName;
	private String usrName;
	private String modifyBy;
	private Date modifyDt;
	private String name;
	private String status;
	private String LoginStatus;
	private Date lastLoginDT;
	private Date lastLogoutDT;
	private String mobileNumber;
	private Set<CustomerAccOrder> customerAccOrders = new HashSet<CustomerAccOrder>(
			0);
	
 

	public CustomerProfile() {
	}

	public CustomerProfile(String cif) {
		this.cif = cif;
	}

	public CustomerProfile(String cif, String createBy, Date createDt,
			String fullName, String idNo, String idType, String loginId,
			String modifyBy, Date modifyDt, String name, String status,
			Set<CustomerAccOrder> customerAccOrders) {
		this.cif = cif;
		this.createBy = createBy;
		this.createDt = createDt;
		this.fullName = fullName;
		this.idNo = idNo;
		this.idType = idType;
		this.loginId = loginId;
		this.modifyBy = modifyBy;
		this.modifyDt = modifyDt;
		this.name = name;
		this.status = status;
		this.customerAccOrders = customerAccOrders;
	 
	}

	@Id
	@Column(name = "cif")
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "create_by")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", length = 19)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "full_name")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "id_no")
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "id_type")
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "login_id", length = 100)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "modify_by")
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_dt", length = 19)
	public Date getModifyDt() {
		return this.modifyDt;
	}

	public void setModifyDt(Date modifyDt) {
		this.modifyDt = modifyDt;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerProfile")
	public Set<CustomerAccOrder> getCustomerAccOrders() {
		return this.customerAccOrders;
	}

	public void setCustomerAccOrders(
			Set<CustomerAccOrder> customerAccOrders) {
		this.customerAccOrders = customerAccOrders;
	}



 

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_dt", length = 19)
	public Date getLastLoginDT() {
		return lastLoginDT;
	}

	public void setLastLoginDT(Date lastLoginDT) {
		this.lastLoginDT = lastLoginDT;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_logout_dt", length = 19)
	public Date getLastLogoutDT() {
		return lastLogoutDT;
	}

	public void setLastLogoutDT(Date lastLogoutDT) {
		this.lastLogoutDT = lastLogoutDT;
	}
	
	
	@Column(name = "mobile_number", length = 45)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "org_id", length = 200)
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	
	@Column(name = "login_status", length = 50)
	public String getLoginStatus() {
		return LoginStatus;
	}

	public void setLoginStatus(String loginStatus) {
		LoginStatus = loginStatus;
	}

	
	@Column(name = "org_name", length = 200)
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Column(name = "usr_name", length = 200)
	public String getUsrName() {
		return usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	
	 
	
	
}
