package com.silverlake.mleb.mcb.entity;

// Generated Sep 3, 2013 5:42:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerEvent generated by hbm2java
 */
@Entity
@Table(name = "customer_event")
public class CustomerEvent implements java.io.Serializable {

	private Integer rowId;
	private String cif;
	private String description;
	private String errorCode;
	private String errorMessage;
	private String mlebTranxId;
	private String requestId;
	private Date requestDatetime;
	private Date responseDatetime;
	private String service;
	private String statusCode;
	private String statusDescription;
	private String appVersion;
	private String referenceNo;
	private String deviceId;
	private String deviceRooted;
	private String accountNumber;
	private String product;
	private String channelCode;
	private String orgId;
	private String processTime;

	public CustomerEvent() {
	}

	public CustomerEvent(
			String description, String errorCode, String errorMessage,
			String mlebTranxId, String requestId, Date requestDatetime,
			Date responseDatetime, String service, String statusCode,
			String statusDescription, String appVersion, String referenceNo) {
		this.description = description;
		this.errorCode = errorCode;
		this.errorMessage = errorMessage;
		this.mlebTranxId = mlebTranxId;
		this.requestId = requestId;
		this.requestDatetime = requestDatetime;
		this.responseDatetime = responseDatetime;
		this.service = service;
		this.statusCode = statusCode;
		this.statusDescription = statusDescription;
		this.appVersion = appVersion;
		this.referenceNo = referenceNo;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "CustomerEvent_id")
	@Column(name = "row_id", nullable=false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "error_code", length = 100)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_message", length = 255)
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Column(name = "mleb_tranx_id", length = 45)
	public String getMlebTranxId() {
		return this.mlebTranxId;
	}

	public void setMlebTranxId(String mlebTranxId) {
		this.mlebTranxId = mlebTranxId;
	}

	@Column(name = "request_id", length = 45)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_datetime", length = 19)
	public Date getRequestDatetime() {
		return this.requestDatetime;
	}

	public void setRequestDatetime(Date requestDatetime) {
		this.requestDatetime = requestDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "response_datetime", length = 19)
	public Date getResponseDatetime() {
		return this.responseDatetime;
	}

	public void setResponseDatetime(Date responseDatetime) {
		this.responseDatetime = responseDatetime;
	}

	@Column(name = "service")
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "status_code", length = 100)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "status_description", length = 100)
	public String getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}

	@Column(name = "app_version", length = 45)
	public String getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

	@Column(name = "reference_no", length = 100, nullable = true)
	public String getReferenceNo() {
		return this.referenceNo;
	}

	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo;
	}

	@Column(name = "cif", length = 100)
	public String getCif() {
		return cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "device_id", length = 100, nullable = true)
	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	
	@Column(name = "account_number", length = 100, nullable = true)
	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	
	@Column(name = "product", length = 100, nullable = true)
	public String getProduct() {
		return product;
	}

	public void setProduct(String product) {
		this.product = product;
	}
	
	@Column(name = "channel_code", length = 5, nullable = true)
	public String getChannelCode() {
		return channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	
	@Column(name = "org_id", length = 50)
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "device_rooted", length = 50)
	public String getDeviceRooted() {
		return deviceRooted;
	}

	public void setDeviceRooted(String deviceRooted) {
		this.deviceRooted = deviceRooted;
	}

	@Column(name = "process_time", length = 20)
	public String getProcessTime() {
		return processTime;
	}

	public void setProcessTime(String processTime) {
		this.processTime = processTime;
	}
	
	
	

}
