package com.silverlake.mleb.mcb.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PexProcessTranx generated by hbm2java
 */
@Entity
@Table(name = "mcb_conf")
public class McbConf implements java.io.Serializable {

	private Integer rowId;
	private String mibType;
	private String currency;
	private Date creationDate;
	private String creationBy;
	private String defaultLanguage;
	private Integer deviceLimit;
	private Integer sessionDuration;
	private Integer upfrontNoticeTime;
	private Integer upfrontNoticeMaintncTime;
	private Date updateDate;
	private String updateBy;
	private String status;
	private String description;
	private String exponent;
	private String modulus;
	private Integer resendTokenLimit;
	private Integer inputTokenSize;
	private String generalRegex;
	private Integer cacheExpiredHour;
	private Integer finalCacheExpiredHour;
	private String aoAlphaRegex;
	private String aoAlphaNumericRegex;
	private String loginLimitAccess;
//	private String phoneNumberRegex;
//	private Integer takaCacheExpiredDays;
	private String aoNameRegex;
	
	public McbConf() {
	}

	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "MiBConf_id")
	@Column(name = "row_id", nullable=false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}



	

	


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = true, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	
	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = true, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	

	@Column(name = "status", nullable = true, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


	@Column(name = "mib_type", nullable = true, length = 45)
	public String getMibType() {
		return mibType;
	}


	public void setMibType(String mibType) {
		this.mibType = mibType;
	}


	@Column(name = "currency", nullable = true, length = 45)
	public String getCurrency() {
		return currency;
	}


	public void setCurrency(String currency) {
		this.currency = currency;
	}


	@Column(name = "default_language", nullable = true, length = 45)
	public String getDefaultLanguage() {
		return defaultLanguage;
	}


	public void setDefaultLanguage(String defaultLanguage) {
		this.defaultLanguage = defaultLanguage;
	}


	@Column(name = "device_limit", nullable = false, length = 45)
	public Integer getDeviceLimit() {
		return deviceLimit;
	}


	public void setDeviceLimit(Integer deviceLimit) {
		this.deviceLimit = deviceLimit;
	}


	@Column(name = "session_duration")
	public Integer getSessionDuration() {
		return sessionDuration;
	}


	public void setSessionDuration(Integer sessionDuration) {
		this.sessionDuration = sessionDuration;
	}


	@Column(name = "description", nullable = true, length = 255)
	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	@Column(name = "update_by", nullable = true, length = 45)
	public String getUpdateBy() {
		return updateBy;
	}


	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	
	@Column(name = "creation_by", nullable = true, length = 45)
	public String getCreationBy() {
		return creationBy;
	}
	
	public void setCreationBy(String creationBy) {
		this.creationBy = creationBy;
	}

	@Column(name = "upfront_notice_time", nullable = false)
	public Integer getUpfrontNoticeTime() {
		return upfrontNoticeTime;
	}

	public void setUpfrontNoticeTime(Integer upfrontNoticeTime) {
		this.upfrontNoticeTime = upfrontNoticeTime;
	}


	@Column(name = "upfront_notice_maintnc_time", nullable = false)
	public Integer getUpfrontNoticeMaintncTime() {
		return upfrontNoticeMaintncTime;
	}


	public void setUpfrontNoticeMaintncTime(Integer upfrontNoticeMaintncTime) {
		this.upfrontNoticeMaintncTime = upfrontNoticeMaintncTime;
	}


	@Column(name = "exponent", nullable = true, length = 16)
	public String getExponent() {
		return exponent;
	}


	public void setExponent(String exponent) {
		this.exponent = exponent;
	}


	@Column(name = "modulus", nullable = true, length = 512)
	public String getModulus() {
		return modulus;
	}


	public void setModulus(String modulus) {
		this.modulus = modulus;
	}

	@Column(name = "resend_token_limit")
	public Integer getResendTokenLimit() {
		return resendTokenLimit;
	}


	public void setResendTokenLimit(Integer resendTokenLimit) {
		this.resendTokenLimit = resendTokenLimit;
	}

	@Column(name = "input_token_size")
	public Integer getInputTokenSize() {
		return inputTokenSize;
	}


	public void setInputTokenSize(Integer inputTokenSize) {
		this.inputTokenSize = inputTokenSize;
	}

	@Column(name = "general_regex")
	public String getGeneralRegex() {
		return generalRegex;
	}


	public void setGeneralRegex(String generalRegex) {
		this.generalRegex = generalRegex;
	}

	@Column(name = "cache_expired_hour")
	public Integer getCacheExpiredHour() {
		return cacheExpiredHour;
	}
	public void setCacheExpiredHour(Integer cacheExpiredHour) {
		this.cacheExpiredHour = cacheExpiredHour;
	}
	@Column(name = "final_cache_expired_hour")
	public Integer getFinalCacheExpiredHour() {
		return finalCacheExpiredHour;
	}
	public void setFinalCacheExpiredHour(Integer finalCacheExpiredHour) {
		this.finalCacheExpiredHour = finalCacheExpiredHour;
	}
	@Column(name = "ao_alpha_regex")
	public String getAoAlphaRegex() {
		return aoAlphaRegex;
	}
	public void setAoAlphaRegex(String aoAlphaRegex) {
		this.aoAlphaRegex = aoAlphaRegex;
	}
	@Column(name = "ao_alpha_numeric_regex")
	public String getAoAlphaNumericRegex() {
		return aoAlphaNumericRegex;
	}
	public void setAoAlphaNumericRegex(String aoAlphaNumericRegex) {
		this.aoAlphaNumericRegex = aoAlphaNumericRegex;
	}
//	// P3OCBCSIT-40
//	@Column(name = "phone_number_regex", length = 50)
//	public String getPhoneNumberRegex() {
//		return phoneNumberRegex;
//	}
//	public void setPhoneNumberRegex(String phoneNumberRegex) {
//		this.phoneNumberRegex = phoneNumberRegex;
//	}

//	@Column(name = "taka_cache_expired_days")
//	public Integer getTakaCacheExpiredDays() {
//		return takaCacheExpiredDays;
//	}
//
//
//	public void setTakaCacheExpiredDays(Integer takaCacheExpiredDays) {
//		this.takaCacheExpiredDays = takaCacheExpiredDays;
//	}
	@Column(name = "ao_name_regex")
	public String getAoNameRegex() {
		return aoNameRegex;
	}
	public void setAoNameRegex(String aoNameRegex) {
		this.aoNameRegex = aoNameRegex;
	}


	@Column(name = "login_limit_access" , nullable = true, length = 200)
	public String getLoginLimitAccess() {
		return loginLimitAccess;
	}


	public void setLoginLimitAccess(String loginLimitAccess) {
		this.loginLimitAccess = loginLimitAccess;
	}
	
	
	
	
}
