package com.silverlake.mleb.mcb.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PexProcessTranx generated by hbm2java
 */
@Entity
@Table(name = "mcb_task")
public class McbTask implements java.io.Serializable {

	private String task;
	private Date updateDate;
	private String status;
	private String description;
	
	public McbTask() {
	}

	
	
	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = true, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


	

	@Column(name = "description", nullable = false, length = 256)
	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	
	
	@Id
	@Column(name = "task")
	public String getTask() {
		return task;
	}


	public void setTask(String task) {
		this.task = task;
	}


	
	

	

	
	

}
