package com.silverlake.mleb.mcb.entity;

// Generated Aug 19, 2013 12:40:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeviceProfile generated by hbm2java
 */
@Entity
@Table(name = "unbind_device_profile")
public class UnBindDeviceProfile implements java.io.Serializable {

	private Integer rowId;
	private String deviceId;
	private String cif;
	private String deviceModel;
	private String deviceType;
	private String os;
	private String isRooted;
	private Date dateBind;
	private String status;
	private Date dateUnBind;
	private String unBindBy;
	private String bindBy;
	private String flag;
	private String pnsToken;
	private String biometricStatus;
	private Date biometricDateUpdated;
	private String biometricDeregisterIbFlag;
	private String isPushNotifEnabled;
	private String transId;
	private String tokenFingerPrint;
	private String biometricKey;
	private String deviceLevel;
	private Date dateSwitch;
	private String approvalAction;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "EXTUNBINDDEVPROFILE_ID")
	@Column(name = "row_id", nullable=false)
	public Integer getRowId() {
		return rowId;
	}
	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}
	
	
	
	@Column(name = "is_push_notif_enabled", nullable = true, length = 5)//Y or N
	public String getIsPushNotifEnabled() {
		return isPushNotifEnabled;
	}

	public void setIsPushNotifEnabled(String isPushNotifEnabled) {
		this.isPushNotifEnabled = isPushNotifEnabled;
	}
	
	@Column(name = "biometric_status", nullable = true, length = 20)
	public String getBiometricStatus() {
		return biometricStatus;
	}

	public void setBiometricStatus(String biometricStatus) {
		this.biometricStatus = biometricStatus;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "biometric_date_updated", nullable = true, length = 19)
	public Date getBiometricDateUpdated() {
		return biometricDateUpdated;
	}

	public void setBiometricDateUpdated(Date biometricDateUpdated) {
		this.biometricDateUpdated = biometricDateUpdated;
	}
	
	@Column(name = "biometric_deregister_ib_flag", nullable = true, length = 20)
	public String getBiometricDeregisterIbFlag() {
		return biometricDeregisterIbFlag;
	}

	public void setBiometricDeregisterIbFlag(String biometricDeregisterIbFlag) {
		this.biometricDeregisterIbFlag = biometricDeregisterIbFlag;
	}

	public UnBindDeviceProfile() {
	}

	public UnBindDeviceProfile(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "device_id", length = 250)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	
	@Column(name = "cif", nullable = true, length = 50)
	public String getCif() {
		return cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "device_model", nullable = true, length = 50)
	public String getDeviceModel() {
		return deviceModel;
	}

	public void setDeviceModel(String deviceModel) {
		this.deviceModel = deviceModel;
	}

	
	@Column(name = "device_type", nullable = true, length = 50)
	public String getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	
	@Column(name = "os", nullable = true, length = 50)
	public String getOs() {
		return os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_bind", length = 19)
	public Date getdateBind() {
		return dateBind;
	}

	public void setdateBind(Date dateBind) {
		this.dateBind = dateBind;
	}

	
	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_unBind", nullable = true, length = 19)
	public Date getDateUnBind() {
		return dateUnBind;
	}

	public void setDateUnBind(Date dateUnBind) {
		this.dateUnBind = dateUnBind;
	}

	@Column(name = "unbind_by", nullable = true, length = 50)
	public String getUnBindBy() {
		return unBindBy;
	}

	public void setUnBindBy(String unBindBy) {
		this.unBindBy = unBindBy;
	}

	@Column(name = "bind_by", nullable = true, length = 50)
	public String getBindBy() {
		return bindBy;
	}

	public void setBindBy(String bindBy) {
		this.bindBy = bindBy;
	}

	@Column(name = "flag",nullable = true,length = 2)
	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
	
	@Column(name = "pns_token", nullable = true, length = 400)
	public String getPnsToken() {
		return pnsToken;
	}

	public void setPnsToken(String pnsToken) {
		this.pnsToken = pnsToken;
	}

	@Column(name = "is_rooted", nullable = true, length = 25)
	public String getIsRooted() {
		return isRooted;
	}

	public void setIsRooted(String isRooted) {
		this.isRooted = isRooted;
	}
	
	@Column(name = "trans_id", nullable = true, length = 50)
	public String getTransId() {
		return transId;
	}
	public void setTransId(String transId) {
		this.transId = transId;
	}

	
	@Column(name = "token_finger_print", nullable = true, length = 200)
	public String getTokenFingerPrint() {
		return tokenFingerPrint;
	}

	public void setTokenFingerPrint(String tokenFingerPrint) {
		this.tokenFingerPrint = tokenFingerPrint;
	}

	@Column(name = "biometric_key", nullable = true, length = 255)
	public String getBiometricKey() {
		return biometricKey;
	}

	public void setBiometricKey(String biometricKey) {
		this.biometricKey = biometricKey;
	}
	
	@Column(name = "device_level", nullable = true, length = 50)
	public String getDeviceLevel() {
		return deviceLevel;
	}

	public void setDeviceLevel(String deviceLevel) {
		this.deviceLevel = deviceLevel;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_switch", nullable = true, length = 19)
	public Date getDateSwitch() {
		return dateSwitch;
	}

	public void setDateSwitch(Date dateSwitch) {
		this.dateSwitch = dateSwitch;
	}
	
	@Column(name = "approval_action", nullable = true, length = 50)
	public String getApprovalAction() {
		return approvalAction;
	}

	public void setApprovalAction(String approvalAction) {
		this.approvalAction = approvalAction;
	}
}

