package com.silverlake.mleb.mcb.entity;

// Generated May 22, 2013 6:08:42 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IbwsTranx generated by hbm2java
 */
@Entity
@Table(name = "vcws_tranx")
public class VcwsTranx implements java.io.Serializable {

	private Integer rowId;
	private String version;
	private String errorCode;
	private String errorMessage;
	private String requestId;
	private String requestTimeStamp;
	private String responseTimeStamp;
	private String statusCode;
	private String statusDescription;
	private String serverRequestTimeStamp;
	private String serverResponseTime;
	private String mlebTranxId;
	private String description;
	private String service;
	private String loginId;
	private String orgId;
	public VcwsTranx() {
	}

	public VcwsTranx(String errorCode, String errorMessage,
			String requestId, String requestTimeStamp,
			String responseTimeStamp, String statusCode,
			String statusDescription, String serverRequestTimeStamp,
			String serverResponseTime, String mlebTranxId, String description,
			String service) {
		this.errorCode = errorCode;
		this.errorMessage = errorMessage;
		this.requestId = requestId;
		this.requestTimeStamp = requestTimeStamp;
		this.responseTimeStamp = responseTimeStamp;
		this.statusCode = statusCode;
		this.statusDescription = statusDescription;
		this.serverRequestTimeStamp = serverRequestTimeStamp;
		this.serverResponseTime = serverResponseTime;
		this.mlebTranxId = mlebTranxId;
		this.description = description;
		this.service = service;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "IbwsTranx_id")
	@Column(name = "row_id", nullable=false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}


	@Column(name = "version", length = 45)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "error_code", length = 100)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_message", length = 256)
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Column(name = "request_id", length = 45)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Column(name = "request_time_stamp", length = 45)
	public String getRequestTimeStamp() {
		return this.requestTimeStamp;
	}

	public void setRequestTimeStamp(String requestTimeStamp) {
		this.requestTimeStamp = requestTimeStamp;
	}

	@Column(name = "response_time_stamp", length = 45)
	public String getResponseTimeStamp() {
		return this.responseTimeStamp;
	}

	public void setResponseTimeStamp(String responseTimeStamp) {
		this.responseTimeStamp = responseTimeStamp;
	}

	@Column(name = "status_code", length = 100)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "status_description", length = 256)
	public String getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}

	@Column(name = "server_request_time_stamp", length = 45)
	public String getServerRequestTimeStamp() {
		return this.serverRequestTimeStamp;
	}

	public void setServerRequestTimeStamp(String serverRequestTimeStamp) {
		this.serverRequestTimeStamp = serverRequestTimeStamp;
	}

	@Column(name = "server_response_time", length = 45)
	public String getServerResponseTime() {
		return this.serverResponseTime;
	}

	public void setServerResponseTime(String serverResponseTime) {
		this.serverResponseTime = serverResponseTime;
	}

	@Column(name = "mleb_tranx_id", length = 45)
	public String getMlebTranxId() {
		return this.mlebTranxId;
	}

	public void setMlebTranxId(String mlebTranxId) {
		this.mlebTranxId = mlebTranxId;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "service", length = 256)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "login_id", length = 100)
	public String getLoginId() {
		return loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "org_id", length = 100)
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	
}
