CREATE
    TABLE mleb_hlb.HLB_PNB_PROMOTION
    (
        ROW_ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        MSG_CODE VARCHAR(20) NOT NULL,
        NOTIF_MSG VARCHAR(480) NOT NULL,
        URL_LINK VARCHAR(200),
        BROADCAST_DATE TIMESTAMP,
        CREATED_BY VARCHAR(50),
        CREATED_DT TIMESTAMP,
        MODIFY_BY VARCHAR(50),
        MODIFY_DT TIMESTAMP,
        STATUS VARCHAR(20),
        FLAG VARCHAR(10),
        RETRY_COUNT INTEGER,
        COMPLETED_DATE TIMESTAMP,
        INSERT_REQ_STATUS VARCHAR(80),
        PRIMARY KEY (ROW_ID)
    );
	
alter table mleb_hlb.hlb_pex_process_tranx
add column login_method varchar(45)

alter table mleb_hlb.hlb_pex_process_tranx
add column device_id varchar(100)