INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'RTGS', 'MENU_LIST_TITLE_5103', 'en');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'RTGS', 'MENU_LIST_TITLE_5103', 'in');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'LLG', 'MENU_LIST_TITLE_5104', 'en');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'LLG', 'MENU_LIST_TITLE_5104', 'in');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Online', 'MENU_LIST_TITLE_5105', 'en');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Online', 'MENU_LIST_TITLE_5105', 'in');

INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Fund transfers in IDR above 100 million Rupiah', 'MENU_LIST_DESC_5103', 'en');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Transfer dana dalam Rupiah di atas 100 juta ', 'MENU_LIST_DESC_5103', 'in');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Fund transfers in IDR up to 1 billion Rupiah', 'MENU_LIST_DESC_5104', 'en');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Transfer dana dalam Rupiah sampai dengan 1 Miliar', 'MENU_LIST_DESC_5104', 'in');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Fund transfers in IDR through ATM Bersama / ATM Prima (real time)', 'MENU_LIST_DESC_5105', 'en');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES_I18N (row_id, create_by, create_dt, err_message, err_message_code, language_code) VALUES (MLEB_MCB.MESSAGEPROPERTIESI18N_ID.nextval, 'system', SYSDATE, 'Transfer dana dalam Rupiah melalui jaringan ATM Bersama / ATM Prima (real time)', 'MENU_LIST_DESC_5105', 'in');

INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES (message_id, create_by, create_dt, err_message_code, status) VALUES (MLEB_MCB.MESSAGEPROPERTIES_ID.nextval, 'system', SYSDATE, 'MENU_LIST_TITLE_5103', 'ACTIVE');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES (message_id, create_by, create_dt, err_message_code, status) VALUES (MLEB_MCB.MESSAGEPROPERTIES_ID.nextval, 'system', SYSDATE, 'MENU_LIST_TITLE_5104', 'ACTIVE');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES (message_id, create_by, create_dt, err_message_code, status) VALUES (MLEB_MCB.MESSAGEPROPERTIES_ID.nextval, 'system', SYSDATE, 'MENU_LIST_TITLE_5105', 'ACTIVE');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES (message_id, create_by, create_dt, err_message_code, status) VALUES (MLEB_MCB.MESSAGEPROPERTIES_ID.nextval, 'system', SYSDATE, 'MENU_LIST_DESC_5103', 'ACTIVE');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES (message_id, create_by, create_dt, err_message_code, status) VALUES (MLEB_MCB.MESSAGEPROPERTIES_ID.nextval, 'system', SYSDATE, 'MENU_LIST_DESC_5104', 'ACTIVE');
INSERT INTO MLEB_MCB.MESSAGE_PROPERTIES (message_id, create_by, create_dt, err_message_code, status) VALUES (MLEB_MCB.MESSAGEPROPERTIES_ID.nextval, 'system', SYSDATE, 'MENU_LIST_DESC_5105', 'ACTIVE');