CREATE TABLE MLEB_MCB.ACCESS_RESTRICTION ( 
MENU_ID VARCHAR2(50 CHAR) NOT NULL, 
MENU_PARENT_ID VARCHAR2(50 CHAR), 
MENU_DESCRIPTION VARCHAR2(255 CHAR),
"VALIDATE" NUMBER(1), 
PRIMARY KEY (MENU_ID) );

CREATE INDEX "MLEB_MCB"."ACCS_RETRICTION_IND1" ON "MLEB_MCB"."ACCESS_RESTRICTION" ("MENU_PARENT_ID" ASC);