UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Account Sweep In' WHERE GNCODE = 'ASI' AND GNCODE_TYPE = 'TRANXPRODCODE' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Bill Payment' WHERE GNCODE = 'BPM' AND GNCODE_TYPE = 'TRANXPRODCODE' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Online FX' WHERE GNCODE = 'ONFX' AND GNCODE_TYPE = 'TRANXPRODCODE' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Online FX' WHERE GNCODE = 'ONFX' AND GNCODE_TYPE = 'TRANXPRODCODE_IN' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Time Deposit Account Opening' WHERE GNCODE = 'TDAO' AND GNCODE_TYPE = 'TRANXPRODCODE' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Pembukaan Rekening Deposito' WHERE GNCODE = 'TDAO' AND GNCODE_TYPE = 'TRANXPRODCODE_IN' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Penarikan Tunai' WHERE GNCODE = 'CSWTH' AND GNCODE_TYPE = 'TRANXPRODCODE_IN' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Time Deposit Account Maintenance' WHERE GNCODE = 'TDAM' AND GNCODE_TYPE = 'TRANXPRODCODE' AND STATUS = 'A';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION = 'Pemeliharaan Rekening Deposito' WHERE GNCODE = 'TDAM' AND GNCODE_TYPE = 'TRANXPRODCODE_IN' AND STATUS = 'A';
