UPDATE MLEB_MCB.ACCESS_RESTRICTION SET ROLE_VALIDATE='1', ROLE_TYPE='SB_SGLACC' WHERE MENU_ID='5200';

UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION='Transaksi Mingguan'  WHERE GNCODE_TYPE='FT_RECURRING_IN' AND GNCODE='D0';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION='Transaksi Bulanan'  WHERE GNCODE_TYPE='FT_RECURRING_IN' AND GNCODE='D1';
UPDATE MLEB_MCB.GENERALCODE SET GNCODE_DESCRIPTION='Satu Kali'  WHERE GNCODE_TYPE='FT_RECURRING_IN' AND GNCODE='N';