CREATE TABLE
    ACCESS_RESTRICTION_TRX
    (
        SOURCE_CODE VARCHAR2(255) NOT NULL,
        PROD_CODE VARCHAR2(255) NOT NULL,
        MENU_DESCRIPTION VARCHAR2(255),
        MENU_ID VARCHAR2(255) NOT NULL,
        STATUS VARCHAR2(255) NOT NULL,
        IS_NEW VARCHAR2(1) DEFAULT 'Y',
        IS_EDIT VARCHAR2(1) DEFAULT 'Y',
        IS_CANCEL VARCHAR2(1) DEFAULT 'Y',
        IS_NOTE VARCHAR2(1) DEFAULT 'Y',
        IS_AUDIT VARCHAR2(1) DEFAULT 'Y',
        IS_PRINT VARCHAR2(1) DEFAULT 'Y',
        IS_DELETE VARCHAR2(1) DEFAULT 'Y',
        CONSTRAINT ACCESS_RESTRICTION_TRX_PK PRIMARY KEY (SOURCE_CODE, PROD_CODE, STATUS)
    );