UPDATE MLEB_MCB.MESSAGE_PROPERTIES_I18N SET ERR_MESSAGE_CODE='MENU_LIST_TITLE_5103' WHERE ERR_MESSAGE_CODE='MEN_LIST_TITLE_5103';
UPDATE MLEB_MCB.MESSAGE_PROPERTIES_I18N SET ERR_MESSAGE_CODE='MENU_LIST_TITLE_5104' WHERE ERR_MESSAGE_CODE='MEN_LIST_TITLE_5104';
UPDATE MLEB_MCB.MESSAGE_PROPERTIES_I18N SET ERR_MESSAGE_CODE='MENU_LIST_TITLE_5105' WHERE ERR_MESSAGE_CODE='MEN_LIST_TITLE_5105';
UPDATE MLEB_MCB.MESSAGE_PROPERTIES_I18N SET ERR_MESSAGE_CODE='MENU_LIST_DESC_5103' WHERE ERR_MESSAGE_CODE='MEN_LIST_DESC_5103';
UPDATE MLEB_MCB.MESSAGE_PROPERTIES_I18N SET ERR_MESSAGE_CODE='MENU_LIST_DESC_5104' WHERE ERR_MESSAGE_CODE='MEN_LIST_DESC_5104';
UPDATE MLEB_MCB.MESSAGE_PROPERTIES_I18N SET ERR_MESSAGE_CODE='MENU_LIST_DESC_5105' WHERE ERR_MESSAGE_CODE='MEN_LIST_DESC_5105';