INSERT INTO MLEB_MCB.ACCESS_RESTRICTION (MENU_ID,MENU_PARENT_ID,MENU_DESCRIPTION,ACCESS_VALIDATE,ROLE_VALIDATE,ROLE_TYPE,MENU_VALIDATE,BLOCK_VALIDATE,STATUS,MENU_VALIDATE_ID) VALUES ('5107','VM.0004','FAST',0,0,NULL,1,1,'A','5107');



INSERT INTO MLEB_MCB.GENERALCODE (ROW_ID,GNCODE,GNCODE_DESCRIPTION,GNCODE_TYPE,STATUS,"DATA") VALUES (mleb_mcb.GeneralCode_id.nextval,'5107','FAST','menuAccess','A',NULL);
