-- GENERALCODE
INSERT INTO MLEB_MCB.GENERALCODE (ROW_ID,GNCODE,GNCODE_DESCRIPTION,GNCODE_TYPE,STATUS) VALUES (mleb_mcb.GeneralCode_id.nextval,'maxPendingLimit','5',NULL,'A');

INSERT INTO MLEB_MCB.GENERALCODE (ROW_ID,GNCODE,GNCODE_DESCRIPTION,GNCODE_TYPE,STATUS) VALUES (mleb_mcb.GeneralCode_id.nextval,'primaryDevBind','true',NULL,'A');