ALTER TABLE mleb_mcb.version_control ADD (display_version VARCHAR2(255 CHAR));

DELETE FROM MLEB_MCB.GENERALCODE WHERE GNCODE_TYPE='redirectUrl' AND GNCODE='version_ios';
DELETE FROM MLEB_MCB.GENERALCODE WHERE GNCODE_TYPE='redirectUrl' AND GNCODE='version_android';
DELETE FROM MLEB_MCB.GENERALCODE WHERE GNCODE_TYPE='redirectUrl' AND GNCODE='update_date_ios';
DELETE FROM MLEB_MCB.GENERALCODE WHERE GNCODE_TYPE='redirectUrl' AND GNCODE='update_date_android';
DELETE FROM MLEB_MCB.GENERALCODE WHERE GNCODE_TYPE='redirectUrl' AND GNCODE='update_time_ios';
DELETE FROM MLEB_MCB.GENERALCODE WHERE GNCODE_TYPE='redirectUrl' AND GNCODE='update_time_android';

