UPDATE MLEB_MCB.ACCESS_RESTRICTION SET ROLE_TYPE = null, ROLE_VALIDATE = '0' WHERE MENU_ID='VM.0006';
UPDATE MLEB_MCB.ACCESS_RESTRICTION SET ROLE_TYPE = 'SB_SGLACC,SB_PAYAUTH,SB_PAYVERF', ROLE_VALIDATE = '1' WHERE MENU_ID='10217';
UPDATE MLEB_MCB.ACCESS_RESTRICTION SET ROLE_TYPE = 'SB_SGLACC,SB_PAYMKR,SB_PAYAUTH,SB_PAYVERF', ROLE_VALIDATE = '1' WHERE MENU_ID='5100';
UPDATE MLEB_MCB.ACCESS_RESTRICTION SET ROLE_TYPE = 'SB_SGLACC,SB_PAYMKR,SB_PAYAUTH,SB_PAYVERF', ROLE_VALIDATE = '1' WHERE MENU_ID='5200';
UPDATE MLEB_MCB.ACCESS_RESTRICTION SET ROLE_TYPE = 'SB_SGLACC,SB_PAYMKR,SB_PAYAUTH,SB_PAYVERF', ROLE_VALIDATE = '1' WHERE MENU_ID='VM.0007';

