UPDATE mleb_mcb.ACCESS_RESTRICTION SET MENU_PARENT_ID='VM.0006' WHERE MENU_ID='VM.0007';

UPDATE mleb_mcb.ACCESS_RESTRICTION SET ROLE_VALIDATE='2', ROLE_TYPE='SB_ADMSUBS,SB_STMTVWR' WHERE MENU_ID='VM.0006';
