INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION) 
SELECT MLEB_MCB.VERSIONCONTROL_ID.nextval, 'android', 'A', TO_DATE('2020/05/21 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '3', '1.0.2' FROM MLEB_MCB.VERSION_CONTROL 
WHERE ROWNUM=1 AND NOT EXISTS(SELECT APP_NAME FROM MLEB_MCB.VERSION_CONTROL WHERE APP_NAME = 'android' AND VERSION='3');