INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION) VALUES 
(MLEB_MCB.VERSIONCONTROL_ID.nextval, 'android', 'A', TO_DATE('2020/04/24 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '2', '1.0.1');

INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION) VALUES 
(MLEB_MCB.VERSIONCONTROL_ID.nextval, 'ios', 'A', TO_DATE('2020/04/24 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '2', '1.0.1');