DELETE FROM MLEB_MCB.GENERALCODE WHERE GNCODE_TYPE='LOG_HK_SETTING';
INSERT INTO MLEB_MCB.GENERALCODE (ROW_ID, GNCODE, GNCODE_DESCRIPTION, GNCODE_TYPE, STATUS) VALUES (MLEB_MCB.GENERALCODE_ID.nextval, 'PURGE_TIME_DAY', '180', 'LOG_HK_SETTING', 'A');

-- indexing of tables
ALTER TABLE MLEB_CORE.MLEB_RESPONSE_LOG DROP CONSTRAINT FK44C2832975A0C1F7;
ALTER TABLE MLEB_CORE.MLEB_REF_LOCATION DROP CONSTRAINT FKE642B2C475A0C1F7;
ALTER TABLE MLEB_CORE.MLEB_REF_LOCATION ADD CONSTRAINT FKE642B2C475A0C1F7 FOREIGN KEY (TRANSACTION_ID) REFERENCES MLEB_CORE.MLEB_REQUEST_LOG (TRANSACTION_ID) ON DELETE CASCADE;
ALTER TABLE MLEB_CORE.MLEB_RESPONSE_LOG ADD CONSTRAINT FK44C2832975A0C1F7 FOREIGN KEY (TRANSACTION_ID) REFERENCES MLEB_CORE.MLEB_REQUEST_LOG (TRANSACTION_ID) ON DELETE CASCADE;

-- mleb_request_log and mleb_response log table
CREATE INDEX MLEB_CORE.IDX_REQLOG_TIMESTAMP ON MLEB_CORE.MLEB_REQUEST_LOG("DATE_TIME" ASC);
CREATE INDEX MLEB_CORE.IDX_RESLOG_TRXID ON MLEB_CORE.MLEB_RESPONSE_LOG("TRANSACTION_ID" ASC);

-- vcws tranx table
CREATE INDEX MLEB_MCB.IDX_VCWS_TRX_REQ_TIMESTAMP ON MLEB_MCB.VCWS_TRANX ("REQUEST_TIME_STAMP" ASC);

-- customer event table
CREATE INDEX MLEB_MCB.IDX_CUST_EVT_REQ_DT ON MLEB_MCB.CUSTOMER_EVENT ("REQUEST_DATETIME" ASC);
CREATE INDEX MLEB_MCB.IDX_CUST_EVT_CIF ON MLEB_MCB.CUSTOMER_EVENT ("CIF" ASC);

