INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION)
SELECT MLEB_MCB.VERSIONCONTROL_ID.nextval, 'android', 'A', TO_DATE('2021/12/17 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '18', '1.0.18' FROM MLEB_MCB.VERSION_CONTROL
WHERE ROWNUM=1 AND NOT EXISTS(SELECT APP_NAME FROM MLEB_MCB.VERSION_CONTROL WHERE APP_NAME = 'android' AND VERSION='18');

INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION)
SELECT MLEB_MCB.VERSIONCONTROL_ID.nextval, 'ios', 'A', TO_DATE('2021/12/17 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '16', '1.0.16' FROM MLEB_MCB.VERSION_CONTROL
WHERE ROWNUM=1 AND NOT EXISTS(SELECT APP_NAME FROM MLEB_MCB.VERSION_CONTROL WHERE APP_NAME = 'ios' AND VERSION='16');




