INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION)
SELECT MLEB_MCB.VERSIONCONTROL_ID.nextval, 'android', 'A', TO_DATE('2023/11/13 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '33', '1.0.33' FROM MLEB_MCB.VERSION_CONTROL
WHERE ROWNUM=1 AND NOT EXISTS(SELECT APP_NAME FROM MLEB_MCB.VERSION_CONTROL WHERE APP_NAME = 'android' AND VERSION='33');

INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION)
SELECT MLEB_MCB.VERSIONCONTROL_ID.nextval, 'ios', 'A', TO_DATE('2023/11/13 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '30', '1.0.30' FROM MLEB_MCB.VERSION_CONTROL
WHERE ROWNUM=1 AND NOT EXISTS(SELECT APP_NAME FROM MLEB_MCB.VERSION_CONTROL WHERE APP_NAME = 'ios' AND VERSION='30');