package com.silverlake.mleb.pex.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * HlbPexProcessTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_access_lock", catalog = "mleb_hlb")
public class AccessLock implements java.io.Serializable {


	private String status;
	private Date entryDate;
	private Date accessDate;
	private String keyValue;
	private String Data;
	private Integer version;
	private Integer idleTimeSecond;
	
	public AccessLock() {
	}

	
	


	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entry_date", nullable = false, length = 19)
	public Date getEntryDate() {
		return entryDate;
	}


	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "access_date", nullable = false, length = 19)
	public Date getAccessDate() {
		return accessDate;
	}


	public void setAccessDate(Date accessDate) {
		this.accessDate = accessDate;
	}


	@Id
	@Column(name = "key_value", nullable = false, length = 100, unique = true)
	public String getKeyValue() {
		return keyValue;
	}


	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}


	@Column(name = "data", nullable = false, length = 100)
	public String getData() {
		return Data;
	}


	public void setData(String data) {
		Data = data;
	}

	@Version
	public Integer getVersion() {
		return version;
	}


	public void setVersion(Integer version) {
		this.version = version;
	}




	@Column(name = "idle_time_second" , nullable = false)
	public Integer getIdleTimeSecond() {
		return idleTimeSecond;
	}





	public void setIdleTimeSecond(Integer idleTimeSecond) {
		this.idleTimeSecond = idleTimeSecond;
	}

	
	
	

	
	
	

	
	

	

	
	

}
