package com.silverlake.mleb.pex.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.ForeignKey;

import com.silverlake.hlb.mib.entity.HlbCustomerProfile;

/**
 * HlbPexProcessTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_pex_account", catalog = "mleb_hlb")
public class PexAccount implements java.io.Serializable {

	private Integer rowId;
	private String cif;
	private String mobileNo;
	private Date creationDate;
	private Date updateDate;
	private String mlebTranxID;
	private String status;
	private String accountNumber;
	private String accountName;
	private String accountStatus;
	private String accountType;
	private String accountProductType;
	private String accountDesc;
	private String accountCurrency;
	private HlbCustomerProfile hlbCustomerProfile;
	
	
	@ManyToOne
	@ForeignKey(name = "none") 
	@JoinColumn(name="cif",insertable=false,updatable=false)
	public HlbCustomerProfile getHlbCustomerProfile() {
		return hlbCustomerProfile;
	}


	public void setHlbCustomerProfile(HlbCustomerProfile hlbCustomerProfile) {
		this.hlbCustomerProfile = hlbCustomerProfile;
	}
	
	public PexAccount() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "cif", nullable = false, length = 45)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	
	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = true, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	

	
	@Column(name = "mobile_no", unique = true, nullable = false, length = 45)
	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}


	@Column(name = "mleb_tranx_id", nullable = false, length = 50)
	public String getMlebTranxID() {
		return mlebTranxID;
	}


	public void setMlebTranxID(String mlebTranxID) {
		this.mlebTranxID = mlebTranxID;
	}

	@Column(name = "account_number", nullable = false, length = 45)
	public String getAccountNumber() {
		return accountNumber;
	}


	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "account_name",  length = 50)
	public String getAccountName() {
		return accountName;
	}


	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "account_status", length = 20)
	public String getAccountStatus() {
		return accountStatus;
	}


	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus;
	}

	@Column(name = "account_type", nullable = false, length = 45)
	public String getAccountType() {
		return accountType;
	}


	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "account_description", nullable = false, length = 45)
	public String getAccountDesc() {
		return accountDesc;
	}


	public void setAccountDesc(String accountDesc) {
		this.accountDesc = accountDesc;
	}

	@Column(name = "account_product_type", nullable = false, length = 45)
	public String getAccountProductType() {
		return accountProductType;
	}


	public void setAccountProductType(String accountProductType) {
		this.accountProductType = accountProductType;
	}


	@Column(name = "account_currency", nullable = false, length = 10)
	public String getAccountCurrency() {
		return accountCurrency;
	}


	public void setAccountCurrency(String accountCurrency) {
		this.accountCurrency = accountCurrency;
	}
	
	
	

	
	

	

	
	

}
