package com.silverlake.mleb.pex.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HlbPexProcessTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_pex_conf", catalog = "mleb_hlb")
public class PexConf implements java.io.Serializable {

	private Integer rowId;
	private BigDecimal transactionLimit;
	private Integer transactionATMCharges;
	private Integer transactionITNCharges;
	private Integer transactionDRTCharges;
	private BigDecimal globalDailyLimit;
	private String currency;
	private Date creationDate;
	private Date updateDate;
	private String status;
	private String expiry;
	private String expiryTime;
	private BigDecimal atmDenomination;
	private Integer collectionCodeLength;
	private Integer collectionMaxAttempt;
	private Integer collectionReservePeriod;
	private Integer atmPinLength;
	private String description;
	
	public PexConf() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}



	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	
	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = true, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}




	@Column(name = "transaction_limit", nullable = false, precision = 10, scale=2)
	public BigDecimal getTransactionLimit() {
		return transactionLimit;
	}


	public void setTransactionLimit(BigDecimal transactionLimit) {
		this.transactionLimit = transactionLimit;
	}

	@Column(name = "transaction_atm_charges")
	public int getTransactionATMCharges() {
		return transactionATMCharges;
	}


	public void setTransactionATMCharges(int transactionATMCharges) {
		this.transactionATMCharges = transactionATMCharges;
	}
	
	
	@Column(name = "transaction_itn_charges")
	public int getTransactionITNCharges() {
		return transactionITNCharges;
	}


	public void setTransactionITNCharges(int transactionITNCharges) {
		this.transactionITNCharges = transactionITNCharges;
	}
	
	
	
	@Column(name = "transaction_drt_charges")
	public int getTransactionDRTCharges() {
		return transactionDRTCharges;
	}


	public void setTransactionDRTCharges(int transactionDRTCharges) {
		this.transactionDRTCharges = transactionDRTCharges;
	}

	@Column(name = "expiry", nullable = false, length = 10)
	public String getExpiry() {
		return expiry;
	}


	public void setExpiry(String expiry) {
		this.expiry = expiry;
	}

	@Column(name = "description", nullable = false, length = 10)
	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "atm_denomination", nullable = false, precision = 10, scale=2)
	public BigDecimal getAtmDenomination() {
		return atmDenomination;
	}


	public void setAtmDenomination(BigDecimal atmDenomination) {
		this.atmDenomination = atmDenomination;
	}

	@Column(name = "currency", nullable = false, length = 3)
	public String getCurrency() {
		return currency;
	}


	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "global_daily_limit", nullable = false, precision = 10, scale=2)
	public BigDecimal getGlobalDailyLimit() {
		return globalDailyLimit;
	}


	public void setGlobalDailyLimit(BigDecimal globalDailyLimit) {
		this.globalDailyLimit = globalDailyLimit;
	}

	


	@Column(name = "atm_pin_length", nullable = false)
	public Integer getAtmPinLength() {
		return atmPinLength;
	}


	public void setAtmPinLength(Integer atmPinLength) {
		this.atmPinLength = atmPinLength;
	}

	@Column(name = "collection_code_length", nullable = false)
	public Integer getCollectionCodeLength() {
		return collectionCodeLength;
	}


	public void setCollectionCodeLength(Integer collectionCodeLength) {
		this.collectionCodeLength = collectionCodeLength;
	}


	@Column(name = "expiry_time", nullable = false, length = 10)
	public String getExpiryTime() {
		return expiryTime;
	}


	public void setExpiryTime(String expiryTime) {
		this.expiryTime = expiryTime;
	}


	@Column(name = "collection_max_attempt", nullable = false)
	public Integer getCollectionMaxAttempt() {
		return collectionMaxAttempt;
	}


	public void setCollectionMaxAttempt(Integer collectionMaxAttempt) {
		this.collectionMaxAttempt = collectionMaxAttempt;
	}


	public void setTransactionATMCharges(Integer transactionATMCharges) {
		this.transactionATMCharges = transactionATMCharges;
	}


	public void setTransactionITNCharges(Integer transactionITNCharges) {
		this.transactionITNCharges = transactionITNCharges;
	}


	public void setTransactionDRTCharges(Integer transactionDRTCharges) {
		this.transactionDRTCharges = transactionDRTCharges;
	}

	@Column(name = "collection_reserve_period")
	public Integer getCollectionReservePeriod() {
		return collectionReservePeriod;
	}

	public void setCollectionReservePeriod(Integer collectionReservePeriod) {
		this.collectionReservePeriod = collectionReservePeriod;
	}

	
	
	
	
	
	

	
	

	

	
	

}
