package com.silverlake.mleb.pex.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HlbPexProcessTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_pex_collection_code", catalog = "mleb_hlb")
public class PexCollectionCode implements java.io.Serializable {

	private Integer rowId;
	
	private String collectionNo;
	private String refNo;
	
	
	public PexCollectionCode() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}


	@Column(name = "collection_no",  unique = true, nullable = false, length = 45)
	public String getCollectionNo() {
		return this.collectionNo;
	}

	public void setCollectionNo(String collectionNo) {
		this.collectionNo = collectionNo;
	}


	@Column(name = "ref_no", nullable = false, length = 45)
	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	

	
	

}
