package com.silverlake.mleb.pex.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HlbPexProcessTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_pex_daily_seq_num", catalog = "mleb_hlb")
public class PexDailySeqNum implements java.io.Serializable {

	private Integer rowId;
	private Integer sequenceNum;
	private String type;
	private Date updateDate;

	
	public PexDailySeqNum() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}



	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}


	
	@Column(name = "sequence_num", nullable = false)
	public Integer getSequenceNum() {
		return sequenceNum;
	}


	public void setSequenceNum(Integer sequenceNum) {
		this.sequenceNum = sequenceNum;
	}

	@Column(name = "type", nullable = false, unique = true, length = 45)
	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}

	
	
	

	
	
	

	
	

	

	
	

}
