package com.silverlake.mleb.pex.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.ForeignKey;

import com.silverlake.hlb.mib.entity.HlbCustomerProfile;

/**
 * HlbPexProcessTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_pex_process_tranx", catalog = "mleb_hlb")
public class PexProcessTranx implements java.io.Serializable {

	private Integer rowId;
	private Integer version;
	private String cif;
	private BigDecimal amountCharges;
	private BigDecimal amountEarmark;
	private BigDecimal amountPex;
	private String currency;
	private String collectionNo;
	private String mobileNo;
	private Date creationDate;
	private String refNo;
	private String rbsSeqNo;
	private String rbsholdRef;
	private String status;
	private Date collectionDate;
	private int expiration_period;
	private Date expiredDate;
	private Date cancelledDate;
	private int collectionAttempt;
	private String collectionFlag;
	private String collectionType;
	private String accountNo;
	private String accountType;
	private String accountProductType;
	private String collectionAccNo;
	private String collectionAccType;
	private String collectionAccName;
	private String collectionAccProductType;
	private String collectionBankRouteAbbr;
	private String remarkMessage;
	private String payeeName;
	private String senderName;
	private String errorCode;
	private String errorMessage;
	private String pin;
	private String smsCreationFlag;
	private String smsCancelFlag;
	private String smsSuspendFlag;
	private String updateIBFlag;
	private String updateIBId;
	private String atmTerminalId;
	private String cardNo;
	private String eaiCorrelationId;
	private String locale;
	private String loginMethod;
	private HlbCustomerProfile hlbCustomerProfile;
	//for biometric report at sc
	private String deviceId;
	
	
	public PexProcessTranx() {
	}

	public PexProcessTranx(String cif, BigDecimal amountCharges,
			BigDecimal amountEarmark, BigDecimal amountPex,
			String collectionNo, Date creationDate, String refNo, String status) {
		this.cif = cif;
		this.amountCharges = amountCharges;
		this.amountEarmark = amountEarmark;
		this.amountPex = amountPex;
		this.collectionNo = collectionNo;
		this.creationDate = creationDate;
		this.refNo = refNo;
		this.status = status;
	}

	public PexProcessTranx(String cif, BigDecimal amountCharges,
			BigDecimal amountEarmark, BigDecimal amountPex,
			String collectionNo, Date creationDate, String refNo,
			String status, Date collectionDate) {
		this.cif = cif;
		this.amountCharges = amountCharges;
		this.amountEarmark = amountEarmark;
		this.amountPex = amountPex;
		this.collectionNo = collectionNo;
		this.creationDate = creationDate;
		this.refNo = refNo;
		this.status = status;
		this.collectionDate = collectionDate;
	}
	
	@Column(name = "login_method", nullable = true,length=45)
	public String getLoginMethod() {
		return loginMethod;
	}

	public void setLoginMethod(String loginMethod) {
		this.loginMethod = loginMethod;
	}

	@Column(name = "device_id", nullable = true, length = 100)
	public String getDeviceId() {
			return deviceId;
	}

	public void setDeviceId(String deviceId) {
			this.deviceId = deviceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}
	
	
	
	@Version
	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "cif", nullable = false, length = 45)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "amount_charges", nullable = false, precision = 10, scale=2)
	public BigDecimal getAmountCharges() {
		return this.amountCharges;
	}

	public void setAmountCharges(BigDecimal amountCharges) {
		this.amountCharges = amountCharges;
	}

	@Column(name = "amount_earmark", nullable = false, precision = 10, scale=2)
	public BigDecimal getAmountEarmark() {
		return this.amountEarmark;
	}

	public void setAmountEarmark(BigDecimal amountEarmark) {
		this.amountEarmark = amountEarmark;
	}

	@Column(name = "amount_pex", nullable = false, precision = 10, scale=2)
	public BigDecimal getAmountPex() {
		return this.amountPex;
	}

	public void setAmountPex(BigDecimal amountPex) {
		this.amountPex = amountPex;
	}

	@Column(name = "collection_no", length = 45)
	public String getCollectionNo() {
		return this.collectionNo;
	}

	public void setCollectionNo(String collectionNo) {
		this.collectionNo = collectionNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "ref_no", unique = true, nullable = false, length = 45)
	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "collection_date", length = 19)
	public Date getCollectionDate() {
		return this.collectionDate;
	}

	public void setCollectionDate(Date collectionDate) {
		this.collectionDate = collectionDate;
	}
	
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expired_date", length = 19)
	public Date getExpiredDate() {
		return this.expiredDate;
	}

	public void setExpiredDate(Date expiredDate) {
		this.expiredDate = expiredDate;
	}
	
	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelled_date", length = 19)
	public Date getCancelledDate() {
		return this.cancelledDate;
	}

	public void setCancelledDate(Date cancelledDate) {
		this.cancelledDate = cancelledDate;
	}
	

	
	@Column(name = "mobile_no",  nullable = false, length = 45)
	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	
	@Column(name = "collection_attempt",  nullable = false)
	public int getCollectionAttempt() {
		return collectionAttempt;
	}

	public void setCollectionAttempt(int collectionAttempt) {
		this.collectionAttempt = collectionAttempt;
	}

	@Column(name = "collection_flag",  nullable = false,  length = 45)
	public String getCollectionFlag() {
		return collectionFlag;
	}

	public void setCollectionFlag(String collectionFlag) {
		this.collectionFlag = collectionFlag;
	}

	
	@Column(name = "expiration_period",  nullable = false)
	public int getExpiration_period() {
		return expiration_period;
	}

	public void setExpiration_period(int expiration_period) {
		this.expiration_period = expiration_period;
	}

	@Column(name = "collection_type",  nullable = false, length = 5)
	public String getCollectionType() {
		return collectionType;
	}

	public void setCollectionType(String collectionType) {
		this.collectionType = collectionType;
	}

	@Column(name = "pin",  nullable = true, length = 45)
	public String getPin() {
		return pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	
	@Column(name = "currency",  nullable = false, length = 3)
	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	
	@Column(name = "rbs_seq_no", nullable = false, length = 9)
	public String getRbsSeqNo() {
		return rbsSeqNo;
	}

	public void setRbsSeqNo(String rbsSeqNo) {
		this.rbsSeqNo = rbsSeqNo;
	}

	
	@Column(name = "rbs_hold_ref", nullable = false, length = 40)
	public String getRbsholdRef() {
		return rbsholdRef;
	}

	public void setRbsholdRef(String rbsholdRef) {
		this.rbsholdRef = rbsholdRef;
	}

	@Column(name = "account_no",  nullable = false, length = 45)
	public String getAccountNo() {
		return accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "account_type",  nullable = false, length = 45)
	public String getAccountType() {
		return accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "collection_acc_no",  nullable = true, length = 45)
	public String getCollectionAccNo() {
		return collectionAccNo;
	}

	public void setCollectionAccNo(String collectionAccNo) {
		this.collectionAccNo = collectionAccNo;
	}

	@Column(name = "collection_acc_type",  nullable = true, length = 45)
	public String getCollectionAccType() {
		return collectionAccType;
	}

	public void setCollectionAccType(String collectionAccType) {
		this.collectionAccType = collectionAccType;
	}

	
	@Column(name = "collection_bank_route_abbr",  nullable = true, length = 100)
	public String getCollectionBankRouteAbbr() {
		return collectionBankRouteAbbr;
	}
	
	

	public void setCollectionBankRouteAbbr(String collectionBankRouteAbbr) {
		this.collectionBankRouteAbbr = collectionBankRouteAbbr;
	}
	
	
	

	@Column(name = "remark_message",  nullable = true, length = 256)
	public String getRemarkMessage() {
		return remarkMessage;
	}

	public void setRemarkMessage(String remarkMessage) {
		this.remarkMessage = remarkMessage;
	}

	@Column(name = "payee_name",  nullable = true, length = 100)
	public String getPayeeName() {
		return payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Column(name = "sender_name",  nullable = true, length = 45)
	public String getSenderName() {
		return senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	@Column(name = "error_code",  nullable = true, length = 45)
	public String getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	
	@Column(name = "error_message",  nullable = true, length = 256)
	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Column(name = "sms_creation_flag",  length = 45)
	public String getSmsCreationFlag() {
		return smsCreationFlag;
	}

	public void setSmsCreationFlag(String smsCreationFlag) {
		this.smsCreationFlag = smsCreationFlag;
	}

	@Column(name = "sms_cancel_flag",  length = 45)
	public String getSmsCancelFlag() {
		return smsCancelFlag;
	}

	public void setSmsCancelFlag(String smsCancelFlag) {
		this.smsCancelFlag = smsCancelFlag;
	}

	@Column(name = "update_ib_flag",  length = 45)
	public String getUpdateIBFlag() {
		return updateIBFlag;
	}

	public void setUpdateIBFlag(String updateIBFlag) {
		this.updateIBFlag = updateIBFlag;
	}

	
	
	
	@Column(name = "update_ib_id",  length = 100)
	public String getUpdateIBId() {
		return updateIBId;
	}

	public void setUpdateIBId(String updateIBId) {
		this.updateIBId = updateIBId;
	}

	@Column(name = "sms_suspend_flag",  length = 45)
	public String getSmsSuspendFlag() {
		return smsSuspendFlag;
	}

	public void setSmsSuspendFlag(String smsSuspendFlag) {
		this.smsSuspendFlag = smsSuspendFlag;
	}

	@Column(name = "account_product_type",  nullable = true, length = 45)
	public String getAccountProductType() {
		return accountProductType;
	}

	public void setAccountProductType(String accountProductType) {
		this.accountProductType = accountProductType;
	}

	@Column(name = "collection_acc_product_type",  nullable = true, length = 45)
	public String getCollectionAccProductType() {
		return collectionAccProductType;
	}

	public void setCollectionAccProductType(String collectionAccProductType) {
		this.collectionAccProductType = collectionAccProductType;
	}
	
	@ManyToOne
	@ForeignKey(name = "none") 
	@JoinColumn(name="cif",insertable=false,updatable=false)
	public HlbCustomerProfile getHlbCustomerProfile() {
		return hlbCustomerProfile;
	}

	public void setHlbCustomerProfile(HlbCustomerProfile hlbCustomerProfile) {
		this.hlbCustomerProfile = hlbCustomerProfile;
	}

	
	@Column(name = "collection_acc_name",  nullable = true, length = 100)
	public String getCollectionAccName() {
		return collectionAccName;
	}

	public void setCollectionAccName(String collectionAccName) {
		this.collectionAccName = collectionAccName;
	}

	
	@Column(name = "atm_terminal_id",  nullable = true, length = 100)
	public String getAtmTerminalId() {
		return atmTerminalId;
	}

	public void setAtmTerminalId(String atmTerminalId) {
		this.atmTerminalId = atmTerminalId;
	}

	@Column(name = "card_no",  nullable = true, length = 100)
	public String getCardNo() {
		return cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	
	@Column(name = "eai_correlation_id",  nullable = true, length = 100)
	public String getEaiCorrelationId() {
		return eaiCorrelationId;
	}

	public void setEaiCorrelationId(String eaiCorrelationId) {
		this.eaiCorrelationId = eaiCorrelationId;
	}

	@Column(name = "locale",  nullable = true, length = 100)
	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}
	

	
	

}
