package com.silverlake.mleb.pex.entity;

// Generated Jun 21, 2013 7:13:23 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HlbPexProcessTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_quick_pex_limit", catalog = "mleb_hlb")
public class QuickPexLimit implements java.io.Serializable {

	private Integer rowId;
	private String quickPexType;
	private String description;
	private Date creationDate;
	private Date effectiveDate;
	private String status;
	private Date modifyDt;
	private String modifyBy;
	private BigDecimal iosAmountLimit;
	private BigDecimal androidAmountLimit;
	
	public QuickPexLimit() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}



	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	
	
	

	

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


	@Column(name = "quick_pex_type", nullable = false, length = 45)
	public String getQuickPexType() {
		return quickPexType;
	}


	public void setQuickPexType(String quickPexType) {
		this.quickPexType = quickPexType;
	}
	
	
	@Column(name = "description", length=256 )
	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "effective_date", nullable = false, length = 19)
	public Date getEffectiveDate() {
		return effectiveDate;
	}


	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_dt", nullable = true, length = 19)
	public Date getModifyDt() {
		return modifyDt;
	}


	public void setModifyDt(Date modifyDt) {
		this.modifyDt = modifyDt;
	}

	@Column(name = "modify_by", length=256 )
	public String getModifyBy() {
		return modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}



	@Column(name = "ios_amount_limit",  nullable = true, precision = 10, scale=2)
	public BigDecimal getIosAmountLimit() {
		return iosAmountLimit;
	}


	public void setIosAmountLimit(BigDecimal iosAmountLimit) {
		this.iosAmountLimit = iosAmountLimit;
	}

	@Column(name = "android_amount_limit",  nullable = true, precision = 10, scale=2)
	public BigDecimal getAndroidAmountLimit() {
		return androidAmountLimit;
	}


	public void setAndroidAmountLimit(BigDecimal androidAmountLimit) {
		this.androidAmountLimit = androidAmountLimit;
	}
}
