package com.silverlake.mleb.pex.entity;

// Generated May 22, 2013 6:08:42 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HlbIbwsTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_RBS_pex_log",catalog = "mleb_hlb")
public class RBSPExLog implements java.io.Serializable {

	private Integer rowId;
	private String transactionCode;
	private String journalSeq;
	private Date requestDateTime;
	private Date responseDateTime;
	private Integer processTime;
	private String responseCode;
	private String errorCode;
	private String service;
	private String refNo;
	private String cif;
	private String fromAccNo;
	private String toAccNo;
	

	
	
	
	
	public RBSPExLog() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_datetime", nullable = false, length = 19)
	public Date getRequestDateTime() {
		return this.requestDateTime;
	}

	public void setRequestDateTime(Date requestDateTime) {
		this.requestDateTime = requestDateTime;
	}

	@Column(name = "process_time")
	public Integer getProcessTime() {
		return this.processTime;
	}

	public void setProcessTime(Integer processTime) {
		this.processTime = processTime;
	}


	@Column(name = "service", length = 45)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}


	@Column(name = "error_code", length = 45)
	public String getErrorCode() {
		return errorCode;
	}



	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}


	
	@Column(name = "ref_no", length = 100)
	public String getRefNo() {
		return refNo;
	}



	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}


	@Column(name = "transaction_code", length = 45)
	public String getTransactionCode() {
		return transactionCode;
	}



	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}


	@Column(name = "jornal_seq", length = 45)
	public String getJournalSeq() {
		return journalSeq;
	}



	public void setJournalSeq(String journalSeq) {
		this.journalSeq = journalSeq;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "response_date_time", nullable = false, length = 19)
	public Date getResponseDateTime() {
		return responseDateTime;
	}



	public void setResponseDateTime(Date responseDateTime) {
		this.responseDateTime = responseDateTime;
	}


	
	@Column(name = "response_code" ,length = 45)
	public String getResponseCode() {
		return responseCode;
	}



	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}


	@Column(name = "cif", length = 45)
	public String getCif() {
		return cif;
	}



	public void setCif(String cif) {
		this.cif = cif;
	}



	@Column(name = "fromAccNo", length = 45)
	public String getFromAccNo() {
		return fromAccNo;
	}



	public void setFromAccNo(String fromAccNo) {
		this.fromAccNo = fromAccNo;
	}



	@Column(name = "toAccNo", length = 45)
	public String getToAccNo() {
		return toAccNo;
	}



	public void setToAccNo(String toAccNo) {
		this.toAccNo = toAccNo;
	}
	
	
	
	

}
