package com.silverlake.mleb.pex.entity;

// Generated May 22, 2013 6:08:42 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HlbIbwsTranx generated by hbm2java
 */
//@Entity
//@Table(name = "hlb_ws_pex_log",catalog = "mleb_hlb")
public class WSPExLog implements java.io.Serializable {

	private Integer rowId;
	private String version;
	private String requestId;
	private Date requestDateTime;
	private Integer processTime;
	private String statusCode;
	private String statusDescription;
	private String errorCode;
	private String errorDescription;
	private byte[] description;
	private String service;
	private String refNo;

	public WSPExLog() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}


	@Column(name = "version", length = 45)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}


	@Column(name = "request_id", unique = true , length = 45)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_datetime", nullable = false, length = 19)
	public Date getRequestDateTime() {
		return this.requestDateTime;
	}

	public void setRequestDateTime(Date requestDateTime) {
		this.requestDateTime = requestDateTime;
	}

	@Column(name = "process_time")
	public Integer getProcessTime() {
		return this.processTime;
	}

	public void setProcessTime(Integer processTime) {
		this.processTime = processTime;
	}

	@Column(name = "status_code", length = 45)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "status_description", length = 100)
	public String getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}

	@Column(name = "description", columnDefinition="BLOB")
	public byte[] getDescription() {
		return this.description;
	}

	public void setDescription(byte[] description) {
		this.description = description;
	}

	@Column(name = "service", length = 45)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}


	@Column(name = "error_code", length = 45)
	public String getErrorCode() {
		return errorCode;
	}



	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}


	@Column(name = "error_description", length = 100)
	public String getErrorDescription() {
		return errorDescription;
	}



	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}
	
	
	
	@Column(name = "ref_no", length = 100)
	public String getRefNo() {
		return refNo;
	}



	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

}
