package comx.silverlake.mleb.mcb.entity;

// Generated May 30, 2013 11:42:58 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ContactUs generated by hbm2java
 */
//@Entity
@Table(name = "contact_us")
public class ContactUs implements java.io.Serializable {

	private Integer contactUsId;
	private byte[] content;
	private String modifiedBy; 
	private Date modifiedDate; 
	private String status;


	public ContactUs() {
	}

	public ContactUs(Integer contactUsId, byte[] content, String modifiedBy, Date modifiedDate, String status) {
		
		this.contactUsId = contactUsId;
		this.content = content;
		this.modifiedBy = modifiedBy ;
		this.modifiedDate = modifiedDate; 		
		this.status = status;

	}

	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "ContactUs_id")
	@Column(name = "contact_us_id",nullable=false)
	public Integer getContactUsId() {
		return contactUsId;
	}

	public void setContactUsId(Integer contactUsId) {
		this.contactUsId = contactUsId;
	}

	@Column(name = "content")
	public byte[] getContent() {
		return content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	@Column(name = "modified_by", length = 50)
	public String getModifiedBy() {
		return modifiedBy;
	}

	

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "modified_date")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


}
