package comx.silverlake.mleb.mcb.entity;

// Generated Aug 19, 2013 12:40:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.silverlake.mleb.mcb.entity.CustomerProfile;

/**
 * DeviceProfile generated by hbm2java
 */
//@Entity
//@Table(name = "device_profile")
public class DeviceProfile implements java.io.Serializable {

	private String deviceId;
	private CustomerProfile customerProfile;
	private String deviceModel;
	private String deviceType;
	private String os;
	private Date dateTagged;
	private String status;
	private Date dateUnTagged;
	private String unTaggedBy;
	private String unTaggedType;
	private String flag;
	private String pnsToken;
	private String biometricStatus;
	private Date biometricDateUpdated;
	private String biometricDeregisterIbFlag;
	private String isPushNotifEnabled;
	
	@Column(name = "is_push_notif_enabled", nullable = true, length = 5)//Y or N
	public String getIsPushNotifEnabled() {
		return isPushNotifEnabled;
	}

	public void setIsPushNotifEnabled(String isPushNotifEnabled) {
		this.isPushNotifEnabled = isPushNotifEnabled;
	}
	
	@Column(name = "biometric_status", nullable = true, length = 20)
	public String getBiometricStatus() {
		return biometricStatus;
	}

	public void setBiometricStatus(String biometricStatus) {
		this.biometricStatus = biometricStatus;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "biometric_date_updated", nullable = true, length = 19)
	public Date getBiometricDateUpdated() {
		return biometricDateUpdated;
	}

	public void setBiometricDateUpdated(Date biometricDateUpdated) {
		this.biometricDateUpdated = biometricDateUpdated;
	}
	
	@Column(name = "biometric_deregister_ib_flag", nullable = true, length = 20)
	public String getBiometricDeregisterIbFlag() {
		return biometricDeregisterIbFlag;
	}

	public void setBiometricDeregisterIbFlag(String biometricDeregisterIbFlag) {
		this.biometricDeregisterIbFlag = biometricDeregisterIbFlag;
	}

	public DeviceProfile() {
	}

	public DeviceProfile(String deviceId) {
		this.deviceId = deviceId;
	}



	@Id
	@Column(name = "device_id")
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cif")
	public CustomerProfile getCustomerProfile() {
		return this.customerProfile;
	}

	public void setCustomerProfile(CustomerProfile customerProfile) {
		this.customerProfile = customerProfile;
	}

	
	@Column(name = "device_model", nullable = true, length = 50)
	public String getDeviceModel() {
		return deviceModel;
	}

	public void setDeviceModel(String deviceModel) {
		this.deviceModel = deviceModel;
	}

	
	@Column(name = "device_type", nullable = true, length = 50)
	public String getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	
	@Column(name = "os", nullable = true, length = 50)
	public String getOs() {
		return os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_tagged", length = 19)
	public Date getDateTagged() {
		return dateTagged;
	}

	public void setDateTagged(Date dateTagged) {
		this.dateTagged = dateTagged;
	}

	
	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_untagged", nullable = true, length = 19)
	public Date getDateUnTagged() {
		return dateUnTagged;
	}

	public void setDateUnTagged(Date dateUnTagged) {
		this.dateUnTagged = dateUnTagged;
	}

	@Column(name = "untagged_by", nullable = true, length = 50)
	public String getUnTaggedBy() {
		return unTaggedBy;
	}

	public void setUnTaggedBy(String unTaggedBy) {
		this.unTaggedBy = unTaggedBy;
	}

	@Column(name = "untagged_type", nullable = true, length = 50)
	public String getUnTaggedType() {
		return unTaggedType;
	}

	public void setUnTaggedType(String unTaggedType) {
		this.unTaggedType = unTaggedType;
	}

	@Column(name = "flag",nullable = true,length = 2)
	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
	
	@Column(name = "pns_token", nullable = true, length = 400)
	public String getPnsToken() {
		return pnsToken;
	}

	public void setPnsToken(String pnsToken) {
		this.pnsToken = pnsToken;
	}

	

}

