package comx.silverlake.mleb.mcb.entity;

// Generated May 30, 2013 11:42:58 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ContactUs generated by hbm2java
 */
//@Entity
@Table(name = "faq")
public class FAQ implements java.io.Serializable {

	private Integer faqId;
	private  byte[] content;
	private  byte[] question;
	private String modifiedBy; 
	private Date modifiedDate; 
	private String status;


	public FAQ() {
	}

	public FAQ(Integer faqId, byte[] content, String modifiedBy, Date modifiedDate, String status) {
		
		this.faqId = faqId;
		this.content = content;
		this.modifiedBy = modifiedBy ;
		this.modifiedDate = modifiedDate; 		
		this.status = status;

	}

	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "FAQ_id")
	@Column(name = "faq_id", nullable=false)
	public Integer getFaqId() {
		return faqId;
	}

	public void setFaqId(Integer faqId) {
		this.faqId = faqId;
	}

	
	@Column(name = "content")
	public byte[] getContent() {
		return content;
	}
	
	public void setContent(byte[] content) {
		this.content = content;
	}

	@Column(name = "modified_by", length = 50)
	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "modified_date")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	@Column(name = "question")
	public byte[] getQuestion() {
		return question;
	}

	public void setQuestion(byte[] question) {
		this.question = question;
	}


	
}
