package comx.silverlake.mleb.mcb.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.ForeignKey;

/**
 * Language generated by hbm2java
 */
//@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

	private String languageCode;
	private String language;
	private String status;
	private Date createDt;
	private String createBy;
	private Date modifyDt;
	private String modifyBy;

	private StoreProfile storeProfile;
	
	public Language() {
	}

	public Language(String languageCode) {
		this.languageCode = languageCode;
	}

	public Language(String languageCode, String language, String status,
			Date createDt, String createBy, Date modifyDt, String modifyBy) {
		this.languageCode = languageCode;
		this.language = language;
		this.status = status;
		this.createDt = createDt;
		this.createBy = createBy;
		this.modifyDt = modifyDt;
		this.modifyBy = modifyBy;
	}

	@Id
	@Column(name = "language_code", nullable=false, length = 30)
	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	@Column(name = "language", length = 30)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", length = 23)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_dt", length = 23)
	public Date getModifyDt() {
		return this.modifyDt;
	}

	public void setModifyDt(Date modifyDt) {
		this.modifyDt = modifyDt;
	}

	@Column(name = "modify_by", length = 50)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@OneToOne(mappedBy = "language", targetEntity=StoreProfile.class)
	@ForeignKey(name = "none") 
	public StoreProfile getStoreProfile() {
		return storeProfile;
	}

	public void setStoreProfile(StoreProfile storeProfile) {
		this.storeProfile = storeProfile;
	}

}
