package comx.silverlake.mleb.mcb.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.ForeignKey;

/**
 * ServiceLocation generated by hbm2java
 */
////@Entity
//@Table(name = "service_location")
public class ServiceLocation implements java.io.Serializable {

	private Integer locId;
	private String status;
	private String phoneNo1;
	private String faxNo1;
	private String longtitude;
	private String latitude;
	private String atmRemark;
	private String bankingRemark;
	private String eBankingRemark;
	private String cashChequeRemark;
	private String bureauDeChangeRemark;
	private String address;
	private String serviceType;
	
	private String branchTime; 
	private String bizTime; 
	private String atmTime;
	private String CcdmTime;
	private String bdcTime;
	private String ebizTime;

	private String serviceType_atm;
	private String serviceType_branch; 
	private String serviceType_ebanking; 
	private String serviceType_bureau; 
	private String serviceType_businessCenter;
	private String serviceType_cashDepoMach; 
	private String serviceType_chequeDepoMach; 
	private String serviceType_hleBroking; 
	private String serviceType_priorityBank; 
	private String serviceType_tradeService; 
	private String serviceType_CreditCard; 
	private String serviceType_DebitCard; 
	private String serviceType_EatFree; 
	
	private String ebanking_hours;
	private String serviceType_islamic;
	private String serviceType_mach;
	private Date createDt;
	private String createBy;
	
	private Date modifyDt;
	private String modifyBy;
	
	private List<ServiceLocationI18n> serviceLocationI18nList;
	//private OperationHours operationHours;

	public ServiceLocation() {
	}

	public ServiceLocation(String status,
			String phoneNo1, String faxNo1, String longtitude, String latitude, String serviceType, 
			String remark, String address, String bizTime, String atmTime, 		
			String promo, String serviceType_atm, String serviceType_branch, 
			String serviceType_ebanking, String serviceType_bureau, String serviceType_businessCenter,
			String serviceType_cashDepoMach, String serviceType_chequeDepoMach, String serviceType_hleBroking, 
			String serviceType_priorityBank, String serviceType_tradeService, String serviceType_CreditCard, 
			String serviceType_DebitCard, String serviceType_EatFree, String ebanking_hours, String serviceType_islamic, String serviceType_mach) {
		
		
		this.status = status;
		this.phoneNo1 = phoneNo1;
		this.faxNo1 = faxNo1;
		this.longtitude = longtitude;
		this.latitude = latitude;
		this.address = address;
		this.serviceType = serviceType;
		
//		this.branchTime = branchTime;		
		this.bizTime = bizTime;
		this.atmTime = atmTime;
		this.serviceType_atm = serviceType_atm;
		this.serviceType_branch =  serviceType_branch; 
		this.serviceType_ebanking =  serviceType_ebanking; 
		this.serviceType_bureau = serviceType_bureau; 
		this.serviceType_businessCenter = serviceType_businessCenter;
		this.serviceType_cashDepoMach = serviceType_cashDepoMach; 
		this.serviceType_chequeDepoMach = serviceType_chequeDepoMach; 
		this.serviceType_hleBroking = serviceType_hleBroking; 
		this.serviceType_priorityBank = serviceType_priorityBank; 
		this.serviceType_tradeService = serviceType_tradeService; 
		this.serviceType_CreditCard = serviceType_CreditCard; 
		this.serviceType_DebitCard = serviceType_DebitCard; 
		this.serviceType_EatFree =  serviceType_EatFree; 
		this.ebanking_hours = ebanking_hours; 
		this.serviceType_islamic =  serviceType_islamic; 
		this.serviceType_mach =  serviceType_mach; 
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "ServiceLocation_id")
	@Column(name = "loc_id" , nullable=false)
	public Integer getLocId() {
		return this.locId;
	}

	public void setLocId(Integer locId) {
		this.locId = locId;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "phone_no_1", length = 20)
	public String getPhoneNo1() {
		return this.phoneNo1;
	}

	public void setPhoneNo1(String phoneNo1) {
		this.phoneNo1 = phoneNo1;
	}

	@Column(name = "fax_no_1", length = 20)
	public String getFaxNo1() {
		return this.faxNo1;
	}

	public void setFaxNo1(String faxNo1) {
		this.faxNo1 = faxNo1;
	}
	
	@Column(name = "longtitude", length = 15)
	public String getLongtitude() {
		return longtitude;
	}

	public void setLongtitude(String longtitude) {
		this.longtitude = longtitude;
	}

	@Column(name = "latitude", length = 15)
	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}
	
	@Column(name = "atm_remark", length = 50)
	public String getAtmRemark() {
		return atmRemark;
	}

	public void setAtmRemark(String atmRemark) {
		this.atmRemark = atmRemark;
	}

	@Column(name = "banking_remark", length = 50)
	public String getBankingRemark() {
		return bankingRemark;
	}

	public void setBankingRemark(String bankingRemark) {
		this.bankingRemark = bankingRemark;
	}

	@Column(name = "ebanking_remark", length = 50)
	public String geteBankingRemark() {
		return eBankingRemark;
	}

	public void seteBankingRemark(String eBankingRemark) {
		this.eBankingRemark = eBankingRemark;
	}

	@Column(name = "cash_cheque_remark", length = 50)
	public String getCashChequeRemark() {
		return cashChequeRemark;
	}

	public void setCashChequeRemark(String cashChequeRemark) {
		this.cashChequeRemark = cashChequeRemark;
	}

	@Column(name = "bereau_de_change_remark", length = 50)
	public String getBureauDeChangeRemark() {
		return bureauDeChangeRemark;
	}

	public void setBureauDeChangeRemark(String bureauDeChangeRemark) {
		this.bureauDeChangeRemark = bureauDeChangeRemark;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "serviceType_atm", length = 2)
	public String getServiceType_atm() {
		return serviceType_atm;
	}

	public void setServiceType_atm(String serviceType_atm) {
		this.serviceType_atm = serviceType_atm;
	}

	@Column(name = "serviceType_branch", length = 2)
	public String getServiceType_branch() {
		return serviceType_branch;
	}

	public void setServiceType_branch(String serviceType_branch) {
		this.serviceType_branch = serviceType_branch;
	}

	@Column(name = "serviceType_ebanking", length = 2)
	public String getServiceType_ebanking() {
		return serviceType_ebanking;
	}

	public void setServiceType_ebanking(String serviceType_ebanking) {
		this.serviceType_ebanking = serviceType_ebanking;
	}

	@Column(name = "serviceType_bureau", length = 2)
	public String getServiceType_bureau() {
		return serviceType_bureau;
	}

	public void setServiceType_bureau(String serviceType_bureau) {
		this.serviceType_bureau = serviceType_bureau;
	}

	@Column(name = "serviceType_businessCenter", length = 2)
	public String getServiceType_businessCenter() {
		return serviceType_businessCenter;
	}

	public void setServiceType_businessCenter(String serviceType_businessCenter) {
		this.serviceType_businessCenter = serviceType_businessCenter;
	}

	@Column(name = "serviceType_cashDepoMach", length = 2)
	public String getServiceType_cashDepoMach() {
		return serviceType_cashDepoMach;
	}

	public void setServiceType_cashDepoMach(String serviceType_cashDepoMach) {
		this.serviceType_cashDepoMach = serviceType_cashDepoMach;
	}

	@Column(name = "serviceType_chequeDepoMach", length = 2)
	public String getServiceType_chequeDepoMach() {
		return serviceType_chequeDepoMach;
	}

	public void setServiceType_chequeDepoMach(String serviceType_chequeDepoMach) {
		this.serviceType_chequeDepoMach = serviceType_chequeDepoMach;
	}

	@Column(name = "serviceType_hleBroking", length = 2)
	public String getServiceType_hleBroking() {
		return serviceType_hleBroking;
	}

	public void setServiceType_hleBroking(String serviceType_hleBroking) {
		this.serviceType_hleBroking = serviceType_hleBroking;
	}

	@Column(name = "serviceType_priorityBank", length = 2)
	public String getServiceType_priorityBank() {
		return serviceType_priorityBank;
	}

	public void setServiceType_priorityBank(String serviceType_priorityBank) {
		this.serviceType_priorityBank = serviceType_priorityBank;
	}

	@Column(name = "serviceType_tradeService", length = 2)
	public String getServiceType_tradeService() {
		return serviceType_tradeService;
	}

	public void setServiceType_tradeService(String serviceType_tradeService) {
		this.serviceType_tradeService = serviceType_tradeService;
	}

	@Column(name = "serviceType_CreditCard", length = 2)
	public String getServiceType_CreditCard() {
		return serviceType_CreditCard;
	}

	public void setServiceType_CreditCard(String serviceType_CreditCard) {
		this.serviceType_CreditCard = serviceType_CreditCard;
	}

	@Column(name = "serviceType_DebitCard", length = 2)
	public String getServiceType_DebitCard() {
		return serviceType_DebitCard;
	}

	public void setServiceType_DebitCard(String serviceType_DebitCard) {
		this.serviceType_DebitCard = serviceType_DebitCard;
	}

	@Column(name = "serviceType_EatFree", length = 2)
	public String getServiceType_EatFree() {
		return serviceType_EatFree;
	}

	public void setServiceType_EatFree(String serviceType_EatFree) {
		this.serviceType_EatFree = serviceType_EatFree;
	}

	@Column(name = "bizTime", length = 500)
	public String getBizTime() {
		return bizTime;
	}

	public void setBizTime(String bizTime) {
		this.bizTime = bizTime;
	}
	
	@Column(name = "atmTime", length = 500)
	public String getAtmTime() {
		return atmTime;
	}

	public void setAtmTime(String atmTime) {
		this.atmTime = atmTime;
	}

	@Column(name = "ebanking_hours", length = 20)
	public String getEbanking_hours() {
		return ebanking_hours;
	}

	public void setEbanking_hours(String ebanking_hours) {
		this.ebanking_hours = ebanking_hours;
	}
	
	@Column(name = "serviceType_islamic", length = 2)
	public String getServiceType_islamic() {
		return serviceType_islamic;
	}
	
	public void setServiceType_islamic(String serviceType_islamic) {
		this.serviceType_islamic = serviceType_islamic;
	}
	@Column(name = "serviceType_mach", length = 2)
	public String getServiceType_mach() {
		return serviceType_mach;
	}

	public void setServiceType_mach(String serviceType_mach) {
		this.serviceType_mach = serviceType_mach;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_dt", length = 19,nullable = true)
	public Date getCreateDt() {
		return createDt;
	}
	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}
	
	@Column(name = "create_by", length = 50,nullable = true)
	public String getCreateBy() {
		return createBy;
	}
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_dt", length = 19,nullable = true)
	public Date getModifyDt() {
		return modifyDt;
	}
	public void setModifyDt(Date modifyDt) {
		this.modifyDt = modifyDt;
	}
	
	@Column(name = "modify_by", length = 50,nullable = true)
	public String getModifyBy() {
		return modifyBy;
	}
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	
	@Column(name = "ccdm_time", length = 500)
	public String getCcdmTime() {
		return CcdmTime;
	}

	public void setCcdmTime(String ccdmTime) {
		CcdmTime = ccdmTime;
	}
	@Column(name = "bdc_time", length = 500)
	public String getBdcTime() {
		return bdcTime;
	}

	public void setBdcTime(String bdcTime) {
		this.bdcTime = bdcTime;
	}
	@Column(name = "ebiz_time", length = 500)
	public String getEbizTime() {
		return ebizTime;
	}

	public void setEbizTime(String ebizTime) {
		this.ebizTime = ebizTime;
	}
	@Column(name = "branchTime", length = 500)
	public String getBranchTime() {
		return branchTime;
	}

	public void setBranchTime(String branchTime) {
		this.branchTime = branchTime;
	}
	@Column(name = "service_type", length = 20)
	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	@ForeignKey(name = "none") 
	@OneToMany(mappedBy="serviceLocation", fetch=FetchType.LAZY)
	public List<ServiceLocationI18n> getServiceLocationI18nList() {
		return serviceLocationI18nList;
	}

	public void setServiceLocationI18nList(
			List<ServiceLocationI18n> serviceLocationI18nList) {
		this.serviceLocationI18nList = serviceLocationI18nList;
	}
	

	/*@OneToOne(mappedBy = "serviceLocation", targetEntity=OperationHours.class)
	@ForeignKey(name = "none") 
	public OperationHours getOperationHours() {
		return operationHours;
	}

	public void setOperationHours(OperationHours operationHours) {
		this.operationHours = operationHours;
	}*/

}
