package comx.silverlake.mleb.mcb.entity;
// Generated Jan 15, 2018 3:26:20 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TakaCacheData generated by hbm2java
 */
//@Entity
@Table(name="taka_cache_data")
public class TakaCacheData  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer rowId;
    private Date createdDate;
    private Date modifiedDate;
    private String userId;
    private String cif;
    private String custEmail;
    private String goalCode;
    private String targetAmount;
    private String initialAmount;
    private String tenor;
    private String status;
     
    @Id
  	@GeneratedValue(strategy=GenerationType.AUTO, generator = "id_Sequence")
  	@SequenceGenerator(name = "id_Sequence", sequenceName = "TAKA_CACHE_DATA_ID")
    @Column(name="row_id", unique=true, nullable=false)
	public Integer getRowId() {
		return rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name="cif")
	public String getCif() {
		return cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name="cust_email")
	public String getCustEmail() {
		return custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	@Column(name="goal_code", length=20)
	public String getGoalCode() {
		return goalCode;
	}

	public void setGoalCode(String goalCode) {
		this.goalCode = goalCode;
	}

	@Column(name="initial_amount", length=50)
	public String getInitialAmount() {
		return initialAmount;
	}

	public void setInitialAmount(String initialAmount) {
		this.initialAmount = initialAmount;
	}

	@Column(name = "status", length=20)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "target_amount", length=50)
	public String getTargetAmount() {
		return targetAmount;
	}

	public void setTargetAmount(String targetAmount) {
		this.targetAmount = targetAmount;
	}

	@Column(name = "tenor", length=5)
	public String getTenor() {
		return tenor;
	}

	public void setTenor(String tenor) {
		this.tenor = tenor;
	}

	@Column(name="user_id")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

 	
}


