INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION)
SELECT MLEB_MCB.VERSIONCONTROL_ID.nextval, 'android', 'A', TO_DATE('2021/08/13 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '15', '1.0.15' FROM MLEB_MCB.VERSION_CONTROL
WHERE ROWNUM=1 AND NOT EXISTS(SELECT APP_NAME FROM MLEB_MCB.VERSION_CONTROL WHERE APP_NAME = 'android' AND VERSION='15');

INSERT INTO MLEB_MCB.VERSION_CONTROL (ROW_ID, APP_NAME, STATUS, UPDATE_DATE, VERSION, DISPLAY_VERSION)
SELECT MLEB_MCB.VERSIONCONTROL_ID.nextval, 'ios', 'A', TO_DATE('2021/08/13 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), '12', '1.0.12' FROM MLEB_MCB.VERSION_CONTROL
WHERE ROWNUM=1 AND NOT EXISTS(SELECT APP_NAME FROM MLEB_MCB.VERSION_CONTROL WHERE APP_NAME = 'ios' AND VERSION='12');




